Cookie initialy baked by NetworkToCode Cookie Drift Manager Tool
nautobot/nautobot-plugin-device-onboarding pull request #116
Opened 2023-10-20 09:57 UTC by snaselj

Template:

```
{
    "template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
    "dir": "nautobot-app",
    "ref": "develop",
    "path": null
}
```

Cookie:

```
{
    "remote": "https://github.com/nautobot/nautobot-plugin-device-onboarding.git",
    "path": "/opt/ntc/drift-manager/outputs/nautobot-plugin-device-onboarding",
    "repository_path": "/opt/ntc/drift-manager/outputs/nautobot-plugin-device-onboarding",
    "dir": "",
    "branch_prefix": "drift-manager",
    "context": {
        "codeowner_github_usernames": "@smith-ntc",
        "full_name": "Network to Code, LLC",
        "email": "info@networktocode.com",
        "github_org": "nautobot",
        "plugin_name": "nautobot_device_onboarding",
        "verbose_name": "Device Onboarding",
        "plugin_slug": "nautobot-device-onboarding",
        "project_slug": "nautobot-plugin-device-onboarding",
        "repo_url": "https://github.com/nautobot/nautobot-plugin-device-onboarding",
        "base_url": "nautobot-device-onboarding",
        "min_nautobot_version": "2.0.0",
        "max_nautobot_version": "2.9999",
        "camel_name": "NautobotDeviceOnboarding",
        "project_short_description": "Device Onboarding",
        "model_class_name": "None",
        "open_source_license": "Apache-2.0",
        "docs_base_url": "https://docs.nautobot.com",
        "docs_app_url": "https://docs.nautobot.com/projects/device-onboarding/en/latest",
        "_template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
        "_output_dir": "/opt/ntc/drift-manager/outputs",
        "_repo_dir": "/opt/ntc/drift-manager/outputs/.cookiecutters/cookiecutter-nautobot-app/nautobot-app",
        "_checkout": "develop"
    },
    "base_branch": "develop",
    "remote_name": "origin",
    "pull_request_strategy": "PullRequestStrategy.CREATE",
    "post_actions": [
        "PostAction.BLACK"
    ],
    "baked_commit_ref": "",
    "draft": true
}
```

CLI Arguments:

```
{
    "cookie_dir": "",
    "input": false,
    "json_filename": "setup-cookie-device-onboarding.json",
    "output_dir": "./outputs",
    "push": true,
    "template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
    "template_dir": "nautobot-app",
    "template_ref": "develop",
    "pull_request": null,
    "post_action": [
        "black"
    ],
    "disable_post_actions": false,
    "draft": true
}
```

2023-10-20 11:47 UTC, snaselj commented
This PR is ready for review.

cc.: @whitej6

2023-10-23 13:39 UTC, whitej6 commented on development/docker-compose.base.yml
> -      - "watchmedo auto-restart --directory './' --pattern '*.py' --recursive -- nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL --events"  ## $$ because of docker-compose
Needs to be reverted

2023-10-23 13:39 UTC, whitej6 commented on development/docker-compose.base.yml
> -      - "watchmedo auto-restart --directory './' --pattern '*.py' --recursive -- nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL --events"  ## $$ because of docker-compose
NVM covered by dev

2023-10-23 13:42 UTC, whitej6 requested changes

2023-10-23 13:42 UTC, whitej6 commented on docs/dev/arch_decision.md
> +    For examples see [Golden Config](https://github.com/nautobot/nautobot-plugin-golden-config/tree/develop/docs/dev/dev_adr.md) and [nautobot-plugin-reservation](https://github.com/networktocode/nau
Either delete or needs information

2023-10-24 08:36 UTC, snaselj commented on docs/dev/arch_decision.md
> +    For examples see [Golden Config](https://github.com/nautobot/nautobot-plugin-golden-config/tree/develop/docs/dev/dev_adr.md) and [nautobot-plugin-reservation](https://github.com/networktocode/nau
Should be done by package maintainers @whitej6

2023-11-09 08:36 UTC, snaselj commented on docs/dev/arch_decision.md
> +    For examples see [Golden Config](https://github.com/nautobot/nautobot-plugin-golden-config/tree/develop/docs/dev/dev_adr.md) and [nautobot-plugin-reservation](https://github.com/networktocode/nau
File has been removed.

2023-11-16 16:39 UTC, scetron commented on docs/dev/arch_decision.md
> +    For examples see [Golden Config](https://github.com/nautobot/nautobot-plugin-golden-config/tree/develop/docs/dev/dev_adr.md) and [nautobot-plugin-reservation](https://github.com/networktocode/nau
Done.

2023-11-20 12:47 UTC, whitej6 approved these changes

2023-11-20 12:51 UTC, scetron approved these changes

2023-11-20 14:06 UTC, merged