Update to OnboardingTask tasks views and models to replace UUID with …
nautobot/nautobot-plugin-device-onboarding pull request #23
Opened 2021-09-01 16:08 UTC by pszulczewski

I couldn't use `AutoFied()` as it needs to be `primary_key` and and there is already other `primary_key` existing - I think UUID, so I used `PositiveSmallIntegerFieldinstead()` instead.

I created a private method to get the latest ID, but maybe there is a more elegant way to do that.

There was a request in the issue #22 to add tests for existing objects without label, but I am not sure how to update tests if models are already updated and all objects are created from within updated models.

Comments are welcome.

2021-09-02 11:10 UTC, mzbroch requested changes

2021-09-02 11:10 UTC, mzbroch commented on nautobot_device_onboarding/templates/nautobot_device_onboarding/onboardingtask.html
> +                    <td>{{ object.label|placeholder }}</td>
What is the behaviour when there is no label for a given Task? We still want to allow users to click on the link and naviage to the details of the task

2021-09-02 11:10 UTC, mzbroch commented on nautobot_device_onboarding/views.py
> +    queryset = OnboardingTask.objects.filter().exclude(status="running")
Let's not include this change in this PR

2021-09-02 13:23 UTC, pszulczewski commented on nautobot_device_onboarding/models.py
> +    def _get_latest_label(self):
OK

2021-09-02 13:24 UTC, pszulczewski commented on nautobot_device_onboarding/models.py
> +            self.label = self._get_latest_label()
OK

2021-09-02 13:24 UTC, pszulczewski commented on nautobot_device_onboarding/models.py
> +    label = models.PositiveSmallIntegerField(default=0, editable=False, help_text="label to sort tasks")
OK

2021-09-02 13:28 UTC, glennmatthews commented on nautobot_device_onboarding/templates/nautobot_device_onboarding/onboardingtask.html
> +                    <td>{{ object.label|placeholder }}</td>
Per the model implementation, `label` cannot be null or empty; if you're migrating from an existing DB, all existing Tasks will default to label `0`. (That may not be desirable - might want to add some custom migration code to enumerate and assign unique labels to existing Tasks?)

2021-09-02 13:28 UTC, pszulczewski commented on nautobot_device_onboarding/views.py
> +    queryset = OnboardingTask.objects.filter().exclude(status="running")
OK

2021-09-02 13:41 UTC, pszulczewski commented on nautobot_device_onboarding/models.py
> +            self.label = self._get_latest_label()
Needs to be like this:
```
latest_label = OnboardingTask.objects.all().order_by("-label").first()
self.label = (latest_label.label if latest_label else 0) + 1
```
because we need attribute value from an existing object -> the very first task creation.

2021-09-06 11:03 UTC, mzbroch commented on nautobot_device_onboarding/models.py
> +    label = models.PositiveIntegerField(default=0, editable=False, help_text="Label for sorting tasks")
Let's make this field unique

2021-09-06 11:05 UTC, mzbroch commented on nautobot_device_onboarding/templates/nautobot_device_onboarding/onboardingtask.html
> +                    <td>{{ object.label|placeholder }}</td>
Agreed, let's extend the original scope with label assignment.
@pszulczewski We should be good with following: for all of the existing database tasks, sort them by ChangeLog's creation date, we should start with Task id = 1.

2021-09-06 11:06 UTC, mzbroch commented on nautobot_device_onboarding/views.py
> +    # queryset = OnboardingTask.objects.filter().exclude(status="running")  # TODO for above
Please remove this line

2021-09-06 15:06 UTC, pszulczewski commented on nautobot_device_onboarding/templates/nautobot_device_onboarding/onboardingtask.html
> +                    <td>{{ object.label|placeholder }}</td>
Done

2021-09-06 15:06 UTC, pszulczewski commented on nautobot_device_onboarding/views.py
> +    # queryset = OnboardingTask.objects.filter().exclude(status="running")  # TODO for above
Done

2021-09-06 15:07 UTC, pszulczewski commented on nautobot_device_onboarding/models.py
> +    label = models.PositiveIntegerField(default=0, editable=False, help_text="Label for sorting tasks")
Must have default otherwise database fails with Null value.

2021-09-06 20:43 UTC, mzbroch approved these changes
LGTM, please squash all your commits into one indicating the scope of PR.

2021-09-08 07:38 UTC, merged